// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWxbIhHH3B-AgUdXUqoBZKMwxxR2sSH0',
    appId: '1:745684952956:web:9925a68193e51c6d7326f9',
    messagingSenderId: '745684952956',
    projectId: 'len-den-e0542',
    authDomain: 'len-den-e0542.firebaseapp.com',
    storageBucket: 'len-den-e0542.firebasestorage.app',
    measurementId: 'G-J22QEK4HR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFSEHVyhrC11-ZsYWHzxGMqE237PT08cw',
    appId: '1:745684952956:android:f42aa24502b574f07326f9',
    messagingSenderId: '745684952956',
    projectId: 'len-den-e0542',
    storageBucket: 'len-den-e0542.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAltesFiQ1r1XX81hykyIkLZ08B9Ap-sZE',
    appId: '1:745684952956:ios:c6aca6d7c8520e377326f9',
    messagingSenderId: '745684952956',
    projectId: 'len-den-e0542',
    storageBucket: 'len-den-e0542.firebasestorage.app',
    iosBundleId: 'com.mimi.denaPawna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAltesFiQ1r1XX81hykyIkLZ08B9Ap-sZE',
    appId: '1:745684952956:ios:c6aca6d7c8520e377326f9',
    messagingSenderId: '745684952956',
    projectId: 'len-den-e0542',
    storageBucket: 'len-den-e0542.firebasestorage.app',
    iosBundleId: 'com.mimi.denaPawna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWxbIhHH3B-AgUdXUqoBZKMwxxR2sSH0',
    appId: '1:745684952956:web:85790e5d0b347fc87326f9',
    messagingSenderId: '745684952956',
    projectId: 'len-den-e0542',
    authDomain: 'len-den-e0542.firebaseapp.com',
    storageBucket: 'len-den-e0542.firebasestorage.app',
    measurementId: 'G-4GCC788CJ9',
  );
}
